### PR TITLE
feat(BAE-41): Created download endpoint for final output(reconciled document)

### PR DESCRIPTION
**Pull request by oluwabunmifife**
Link to Linear ticket -> https://linear.app/team-drill-press/issue/BAE-41/create-the-download-endpoint-for-the-final-output
- I've changed the tests dir as requested by Seun
- The download endpoint uses the `requests` package.
- The path/url for the file to be downloaded needs to be passed into the requests.get (`req.get`)
- This would still need refactoring, so please feedback is needed

### CODE REVIEW

**Comment by Joseun** [comment]
Your reconciled.csv file is it an html file or html template.

Great work on the download api. But could you implement this as a frontend functionality. Not backend api requests.

**Comment by oluwabunmifife** [comment]
- @Joseun I'm not sure I get your question but the reconciled.csv is supposed to be the name given to the file downloaded by the user.
- For the second point, please I would need a little more clarity on this.🙏🏾

**Comment by Joseun** [comment]
https://javascript.plainenglish.io/download-html-as-a-pdf-in-react-fc86114c9095

https://stackoverflow.com/questions/44989119/generating-a-pdf-file-from-react-components

**Comment by oluwabunmifife** [comment]
- NOTE: pip install pandas and pdfkit
- Also install wkhtmltopdf from https://wkhtmltopdf.org/downloads.html
- Add the path to the bin folder to your environment variables

**Pull request merged**
