### PR TITLE
fixed table conditional rendering

### PR DESCRIPTION
**Pull request by skillzo**

### CODE REVIEW

**Comment by Celnet-hub** [comment]
This error is coming from Vercel and not from the code base. 

I think that should not cause an issue while merging

**Comment by skillzo** [comment]
Reconcile table has been fixed,  coloring state still needs to be chained to affect all the colors globally,

Also the search bar for the general table still needs to be implemented. we need to affect localData3, by pushing the new table left inside.

**Comment by EarlPappi** [comment]
@Celnet-hub is it possible to look at the deployment issue from vercel and get it fixed?

**Comment by Celnet-hub** [comment]
@EarlPappi are we still using vercel? if yes, then who set it up? so I can work with the person.

**Pull request merged**
