### PR TITLE
feat(BAE-22): Modified unit tests for POST and DELETE endpoints

### PR DESCRIPTION
**Pull request by oluwabunmifife**
BAE-22 (https://linear.app/team-drill-press/issue/BAE-22/database-functionality-2)

- All the tests still use the dummy files.

### CODE REVIEW

**Review by Joseun — CHANGES_REQUESTED** [review]
This requirement.txt dependencies looks too much for the app. Please review

**Review by Joseun — CHANGES_REQUESTED** [review]
Please write the test files to contain 1 functionality. For example, test_delete_document would test all the endpoints and responses for a delete functionality

**Review by oluwabunmifife — COMMENTED** [review]
I've made the adjustments.

**Comment by Joseun** [comment]
There are conflicts in the fies I think you should take a look at

**Pull request closed without merging**
