### PR TITLE
Feat/bae 38 create the data upload function

### PR DESCRIPTION
**Pull request by Joseun**
Adjusted the file systems and naming conventions in the repository.
Added __init__ and README files in directories
Created independent test files for all functions and routes
Refactored code blocks in all files
Algorithm now uses GPT3 to return a json string with the comparison

https://linear.app/team-drill-press/issue/BAE-38/create-the-data-upload-function

### CODE REVIEW

**Comment by Joseun** [comment]
Please help resolve conflict

**Comment by EarlPappi** [comment]
Any BE dev should help review please @bernard-rr

**Comment by Joseun** [comment]
> Any BE dev should help review please @bernard-rr 

take a look at the tests folder @EarlPappi

**Comment by marvellousadesanya** [comment]
Your branch has conflicts. Can't be merged.

**Pull request merged**
